name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t hmzza/python-auth:latest .

    - name: Push Docker Image to Dockerhub
      run: |
        echo $DOCKERHUB_TOKEN | docker login -u hmmza --password-stdin
        docker push hmzza/python-auth:latest
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
